#person:
#  name: zhangsan
#  age: 19
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 20

server:
  port: 8080

spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: prod
---
server:
  port: 8082

spring:
  profiles: dev